---
name: Nightly Builders

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 1

jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    if: ${{ github.event_name == 'schedule' }}
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: should_run
        continue-on-error: true
        name: Check latest commit is less than a day
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo
          "::set-output name=should_run::false"

  build-macos-debug:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    uses: ./.github/workflows/ci-debug-builds-macos.yml
    secrets: inherit

  build-linux-debug:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    uses: ./.github/workflows/ci-debug-builds-linux.yml
    secrets: inherit

  build-windows-debug:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    uses: ./.github/workflows/ci-debug-builds-windows.yml
    secrets: inherit
