---
name: CI tests (Common)

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  run-tests:
    name: Common CI tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Configure Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy,rustfmt
          override: true
          default: true
      - name: Install `cargo-audit`
        run: cargo install --locked cargo-audit
      - name: Install `cargo-vet`
        run: cargo install --locked cargo-vet --version "0.9.0"
      - name: Run `cargo-vet`
        run: cargo vet --locked
        working-directory: src/oldbestool
      - name: Run `cargo-audit`
        run: cargo audit -D unsound -D yanked -D unmaintained  --ignore "RUSTSEC-2020-0168" 
        working-directory: src/oldbestool
