---
name: CI tests (Windows)

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  run-windows-tests:
    name: CI tests for ${{ matrix.target }}
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        target: [x86_64-pc-windows-gnu]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Cache Rust assets
        id: rust-cache
        uses: Swatinem/rust-cache@v2
      - name: Configure Rust
        if: ${{ steps.rust-cache.outputs.cache-hit != 'true' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy,rustfmt
          override: true
          target: ${{ matrix.target }}
          default: true
      - name: Run Windows tests of `bestool`
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target=${{ matrix.target }}
      - name: Run Windows checks of `bestool`
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target=${{ matrix.target }}
      - name: Run Windows Clippy tests of `bestool`
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --target=${{ matrix.target }}
